server:
  port: 8081
  servlet:
    context-path: /api/
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/communityDB  #communityDB_copy
    username: root
    password: root #100279Sy
#    Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      uri: mongodb://localhost:27017/communityDB?gssapiServiceName=mongodb

# mybatis-plus .mapper文件配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration: # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

